# Generated by Django 2.2.28 on 2023-06-30 12:37

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('households', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Property',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, null=True)),
                ('updated_at', models.DateTimeField(default=django.utils.timezone.now, null=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('name', models.CharField(max_length=50)),
                ('price', models.FloatField()),
                ('description', models.CharField(default='Asset', max_length=255)),
                ('cover_image', models.CharField(default='/images/products/product_1.png', max_length=255)),
                ('is_active', models.BooleanField(default=True)),
                ('household', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='properties', to='households.Household')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='properties', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Properties',
                'db_table': 'properties',
                'ordering': ['name'],
                'unique_together': {('name', 'owner')},
            },
        ),
        migrations.CreateModel(
            name='PropDetail',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, null=True)),
                ('updated_at', models.DateTimeField(default=django.utils.timezone.now, null=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('title', models.CharField(max_length=255)),
                ('amount', models.FloatField()),
                ('type', models.CharField(choices=[('in', 'Inflow'), ('out', 'Outflow')], default='out', max_length=10)),
                ('property', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='prop_details', to='properties.Property')),
            ],
            options={
                'verbose_name_plural': 'Property Details',
                'db_table': 'property_details',
                'ordering': ['title'],
            },
        ),
    ]
