# Generated by Django 2.2.24 on 2021-09-12 18:52

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('properties', '0002_auto_20201021_1435'),
    ]

    operations = [
        migrations.AddField(
            model_name='propdetail',
            name='deleted_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='property',
            name='deleted_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='propdetail',
            name='property',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='prop_details', to='properties.Property'),
        ),
        migrations.AlterModelTable(
            name='propdetail',
            table='property_details',
        ),
        migrations.AlterModelTable(
            name='property',
            table='properties',
        ),
    ]
