# Generated by Django 2.2.28 on 2023-06-30 13:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0002_property_household_1'),
    ]

    operations = [
    ]
