# Generated by Django 2.2.24 on 2021-09-20 16:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('stores', '0005_remove_store_property'),
        ('properties', '0003_auto_20210912_2052'),
    ]

    operations = [
        migrations.AddField(
            model_name='property',
            name='store',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='stores', to='stores.Store'),
        ),
        migrations.AlterField(
            model_name='propdetail',
            name='property',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='prop_details', to='properties.Property'),
        ),
    ]
