# Generated by Django 2.2.13 on 2020-07-21 05:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0004_auto_20200720_1251'),
    ]

    operations = [
        migrations.CreateModel(
            name='PropDetail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('title', models.CharField(max_length=255)),
                ('amount', models.FloatField()),
                ('type', models.CharField(choices=[('in', 'Inflow'), ('out', 'Outflow')], default='out', max_length=10)),
                ('property', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='properties.Property')),
            ],
            options={
                'ordering': ['title'],
            },
        ),
    ]
