# Generated by Django 2.2.24 on 2021-09-20 17:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0004_auto_20210920_1850'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='property',
            name='store',
        ),
    ]
