# Generated by Django 2.2.13 on 2020-08-12 09:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0005_propdetail'),
    ]

    operations = [
        migrations.AddField(
            model_name='propdetail',
            name='description',
            field=models.CharField(default='Asset', max_length=255),
        ),
    ]
