# Generated by Django 2.2.13 on 2020-08-12 09:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0006_propdetail_description'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='propdetail',
            name='description',
        ),
        migrations.AddField(
            model_name='property',
            name='description',
            field=models.CharField(default='Asset', max_length=255),
        ),
    ]
