# Generated by Django 2.2.24 on 2023-03-19 19:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('households', '0003_auto_20230319_2110'),
        ('properties', '0006_auto_20221222_1705'),
    ]

    operations = [
        migrations.AddField(
            model_name='property',
            name='household',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='households.Household'),
        ),
    ]
