# Generated by Django 2.2.13 on 2020-08-12 09:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0007_auto_20200812_0931'),
    ]

    operations = [
        migrations.AddField(
            model_name='property',
            name='cover_image',
            field=models.CharField(default='/images/products/product_1.png', max_length=255),
        ),
    ]
