# Generated by Django 2.2.24 on 2023-03-19 19:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0007_property_household'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='property',
            name='household',
        ),
    ]
