# Generated by Django 2.2.24 on 2023-03-23 05:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('households', '0009_household_members'),
        ('properties', '0008_remove_property_household'),
    ]

    operations = [
        migrations.AddField(
            model_name='property',
            name='household',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='properties', to='households.Household'),
        ),
    ]
