# Generated by Django 2.2.10 on 2020-07-11 18:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('properties', '0001_initial'),
        ('prop_details', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='propdetails',
            name='property',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='properties.Property'),
        ),
    ]
