# Generated by Django 2.2.28 on 2023-06-29 06:25

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Salary',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, null=True)),
                ('updated_at', models.DateTimeField(default=django.utils.timezone.now, null=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('pension', models.FloatField()),
                ('maternity', models.FloatField()),
                ('tax', models.FloatField()),
                ('net_salary', models.FloatField()),
                ('gross_salary', models.FloatField()),
                ('net_pay', models.FloatField()),
                ('client_ip', models.CharField(default='', max_length=20)),
                ('city', models.CharField(default='', max_length=20)),
                ('country', models.CharField(default='', max_length=20)),
                ('lat', models.CharField(default='', max_length=20)),
                ('long', models.CharField(default='', max_length=20)),
            ],
            options={
                'db_table': 'salaries',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Facility',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, null=True)),
                ('updated_at', models.DateTimeField(default=django.utils.timezone.now, null=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('is_constant', models.FloatField()),
                ('amount', models.FloatField()),
                ('percent_amount', models.FloatField()),
                ('percent_field', models.FloatField()),
                ('percent_field_type', models.CharField(choices=[('ns', 'Net Salary'), ('gs', 'Gross Salary')], default='gs', max_length=20)),
                ('salary', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='facilities', to='manage_system.Salary')),
            ],
            options={
                'db_table': 'facilities',
                'ordering': ['-created_at'],
            },
        ),
    ]
