# Generated by Django 2.2.24 on 2021-09-24 10:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manage_system', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='salary',
            name='client_ip',
            field=models.CharField(default='', max_length=20),
        ),
    ]
