# Generated by Django 2.2.24 on 2021-09-24 10:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('manage_system', '0002_salary_client_ip'),
    ]

    operations = [
        migrations.AddField(
            model_name='facility',
            name='salary',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='facilities', to='manage_system.Salary'),
        ),
    ]
