# Generated by Django 2.2.24 on 2021-09-24 11:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manage_system', '0003_facility_salary'),
    ]

    operations = [
        migrations.AddField(
            model_name='facility',
            name='percent_field_type',
            field=models.CharField(choices=[('ns', 'Net Salary'), ('gs', 'Gross Salary')], default='gs', max_length=20),
        ),
        migrations.AddField(
            model_name='salary',
            name='city',
            field=models.CharField(default='', max_length=20),
        ),
        migrations.AddField(
            model_name='salary',
            name='country',
            field=models.CharField(default='', max_length=20),
        ),
        migrations.AddField(
            model_name='salary',
            name='lat',
            field=models.CharField(default='', max_length=20),
        ),
        migrations.AddField(
            model_name='salary',
            name='long',
            field=models.CharField(default='', max_length=20),
        ),
    ]
