# Generated by Django 2.2.28 on 2023-04-08 19:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('manage_system', '0005_auto_20221222_1705'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='facility',
            name='deleted_by',
        ),
        migrations.RemoveField(
            model_name='salary',
            name='deleted_by',
        ),
    ]
