# Generated by Django 4.2.17 on 2025-05-06 16:02

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('households', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Behavior',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, null=True)),
                ('updated_at', models.DateTimeField(default=django.utils.timezone.now, null=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('name', models.CharField(max_length=200)),
                ('description', models.CharField(max_length=255, null=True)),
                ('weight', models.FloatField(default=100)),
                ('household', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='behaviors', to='households.household')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='behaviors', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'behaviors',
                'ordering': ['-created_at'],
                'unique_together': {('name', 'user')},
            },
        ),
        migrations.CreateModel(
            name='BehaviorScore',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, null=True)),
                ('updated_at', models.DateTimeField(default=django.utils.timezone.now, null=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('action_date', models.DateField(default=django.utils.timezone.now)),
                ('score', models.FloatField()),
                ('behavior', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='scores', to='behavior_ip.behavior')),
            ],
            options={
                'db_table': 'behavior_scores',
            },
        ),
    ]
