# Generated by Django 4.2.17 on 2025-05-07 16:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('behavior_ip', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='behaviorscore',
            name='rate',
            field=models.CharField(choices=[('good', 'Good'), ('bad', 'Bad'), ('so-so', 'So-so')], default='good', max_length=20),
        ),
    ]
