# Generated by Django 4.2.17 on 2025-05-08 16:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('behavior_ip', '0002_behaviorscore_rate'),
    ]

    operations = [
        migrations.AddField(
            model_name='behaviorscore',
            name='description',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
