# Generated by Django 4.2.17 on 2025-08-25 13:11

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Currency',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, null=True)),
                ('updated_at', models.DateTimeField(default=django.utils.timezone.now, null=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('code', models.CharField(help_text='ISO 4217 code, e.g., USD, EUR, GBP.', max_length=3, unique=True)),
                ('name', models.CharField(help_text='Display name, e.g., US Dollar, Euro.', max_length=64)),
                ('symbol', models.CharField(blank=True, help_text='Optional symbol, e.g., $, €, £.', max_length=8)),
                ('minor_unit', models.PositiveSmallIntegerField(default=2, help_text='Number of decimal places, typically 2.')),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Currency',
                'verbose_name_plural': 'Currencies',
                'ordering': ['code'],
            },
        ),
        migrations.CreateModel(
            name='UserSettings',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, null=True)),
                ('updated_at', models.DateTimeField(default=django.utils.timezone.now, null=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('email_notifications', models.BooleanField(default=False, help_text='Get updates and alerts via email.')),
                ('push_notifications', models.BooleanField(default=False, help_text='Get browser notifications for important updates.')),
                ('budget_alerts_enabled', models.BooleanField(default=False, help_text='Get notified when approaching budget limits.')),
                ('budget_alert_threshold', models.PositiveSmallIntegerField(default=80, help_text='Trigger alert at this percent of budget used (1–100).', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(100)])),
                ('default_currency', models.ForeignKey(blank=True, help_text="User's default currency for amounts and budgets.", null=True, on_delete=django.db.models.deletion.PROTECT, related_name='default_users_currency', to='users.currency')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='settings', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'User settings',
                'verbose_name_plural': 'User settings',
            },
        ),
    ]
