# Generated by Django 2.2.28 on 2023-04-06 17:49

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('household_members', '0007_auto_20230322_2015'),
        ('users', '0004_auto_20220905_0949'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='households',
            field=models.ManyToManyField(related_name='member_households', through='household_members.HouseholdMember', to=settings.AUTH_USER_MODEL),
        ),
    ]
