# Generated by Django 2.2.28 on 2023-04-07 06:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_user_households'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='households',
        ),
    ]
