# Generated by Django 2.2.28 on 2023-04-08 19:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('households', '0012_auto_20230408_2134'),
        ('users', '0006_remove_user_households'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='household',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='members', to='households.Household'),
        ),
    ]
