# Generated by Django 2.2.28 on 2023-04-09 13:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_user_household'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='household',
        ),
    ]
