# Generated by Django 2.2.28 on 2023-06-29 06:18

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('households', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('household_members', '0003_auto_20230629_0818'),
    ]

    operations = [
        migrations.AddField(
            model_name='household',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='creator', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='household',
            name='members',
            field=models.ManyToManyField(through='household_members.HouseholdMember', to=settings.AUTH_USER_MODEL),
        ),
    ]
