# Generated by Django 2.2.24 on 2023-03-16 17:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('households', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='household',
            name='description',
            field=models.CharField(default='Our house', max_length=255),
        ),
    ]
