# Generated by Django 2.2.24 on 2023-03-19 19:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('households', '0002_household_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='household',
            name='description',
            field=models.CharField(default='Our family', max_length=255),
        ),
    ]
