# Generated by Django 2.2.24 on 2023-03-22 16:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('households', '0004_household_members'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='household',
            name='members',
        ),
    ]
