# Generated by Django 2.2.24 on 2023-03-22 17:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('households', '0005_remove_household_members'),
    ]

    operations = [
        migrations.AddField(
            model_name='household',
            name='members',
            field=models.ManyToManyField(related_name='household_members', through='household_members.HouseholdMember', to='users.User'),
        ),
    ]
