# Generated by Django 2.2.24 on 2023-03-22 17:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('households', '0007_auto_20230322_1939'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='household',
            name='members',
        ),
    ]
