# Generated by Django 2.2.24 on 2023-03-22 18:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('household_members', '0007_auto_20230322_2015'),
        ('households', '0008_remove_household_members'),
    ]

    operations = [
        migrations.AddField(
            model_name='household',
            name='members',
            field=models.ManyToManyField(related_name='house_members', through='household_members.HouseholdMember', to='households.Household'),
        ),
    ]
