# Generated by Django 2.2.28 on 2023-04-08 19:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('households', '0011_household_members'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='household',
            name='deleted_by',
        ),
        migrations.RemoveField(
            model_name='household',
            name='members',
        ),
    ]
