# Generated by Django 2.2.28 on 2023-04-09 13:52

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('household_members', '0008_remove_householdmember_deleted_by'),
        ('households', '0012_auto_20230408_2134'),
    ]

    operations = [
        migrations.AddField(
            model_name='household',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='creator', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='household',
            name='members',
            field=models.ManyToManyField(through='household_members.HouseholdMember', to=settings.AUTH_USER_MODEL),
        ),
    ]
