# Generated by Django 3.0.3 on 2020-02-12 15:41

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Store',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('deleted_at', models.DateTimeField(auto_now=True, null=True)),
                ('amount', models.FloatField()),
                ('record_type', models.CharField(choices=[('use', 'Store'), ('debt', 'Debt'), ('online', 'Online')], default='Store', max_length=20)),
                ('is_property', models.BooleanField(default=False)),
                ('is_inflow', models.BooleanField(default=False)),
                ('description', models.CharField(default='*Home expense', max_length=200)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_query_name='store', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
