# Generated by Django 2.2.28 on 2023-06-29 06:18

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('households', '0001_initial'),
        ('properties', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='RecurringStore',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, null=True)),
                ('updated_at', models.DateTimeField(default=django.utils.timezone.now, null=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('name', models.CharField(max_length=200)),
            ],
            options={
                'db_table': 'recurring_stores',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Store',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, null=True)),
                ('updated_at', models.DateTimeField(default=django.utils.timezone.now, null=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('amount', models.FloatField()),
                ('record_type', models.CharField(choices=[('use', 'Store'), ('debt', 'Debt'), ('online', 'Online')], default='use', max_length=20)),
                ('is_property', models.BooleanField(default=False)),
                ('is_inflow', models.BooleanField(default=False)),
                ('description', models.CharField(default='*Home expense', max_length=200)),
                ('action_date', models.DateField(default=django.utils.timezone.now)),
                ('household', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='stores', to='households.Household')),
                ('property', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='stores', to='properties.Property')),
            ],
            options={
                'db_table': 'stores',
                'ordering': ['-action_date'],
            },
        ),
    ]
