# Generated by Django 2.2.28 on 2023-06-29 06:18

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('stores', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='store',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='stores', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='recurringstore',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='recurring_stores', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterUniqueTogether(
            name='store',
            unique_together={('description', 'action_date', 'user')},
        ),
        migrations.AlterUniqueTogether(
            name='recurringstore',
            unique_together={('name', 'user')},
        ),
    ]
