# Generated by Django 2.2.28 on 2023-06-29 18:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stores', '0002_auto_20230629_0818'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='store',
            name='household',
        ),
    ]
