# Generated by Django 2.2.28 on 2023-06-30 13:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stores', '0002_store_household_1'),
    ]

    operations = [
    ]
