# Generated by Django 3.2.20 on 2024-03-17 07:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('budgeting', '0001_initial'),
        ('stores', '0003_auto_20230630_1527'),
    ]

    operations = [
        migrations.AddField(
            model_name='store',
            name='budget_item',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='stores', to='budgeting.budgetitem'),
        ),
    ]
