# Generated by Django 2.2.28 on 2023-06-29 18:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('households', '0002_auto_20230629_0818'),
        ('stores', '0003_remove_store_household'),
    ]

    operations = [
        migrations.AddField(
            model_name='store',
            name='household',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='stores', to='households.Household'),
        ),
    ]
