# Generated by Django 2.2.24 on 2021-09-19 10:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0003_auto_20210912_2052'),
        ('stores', '0003_auto_20210912_2052'),
    ]

    operations = [
        migrations.AddField(
            model_name='store',
            name='property',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='properties.Property'),
        ),
    ]
