# Generated by Django 2.2.13 on 2020-08-24 07:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stores', '0003_auto_20200720_1251'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='store',
            options={'ordering': ['-action_date']},
        ),
        migrations.AlterUniqueTogether(
            name='store',
            unique_together={('description', 'action_date')},
        ),
    ]
