# Generated by Django 2.2.13 on 2020-08-24 07:47

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('stores', '0004_auto_20200824_0743'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='store',
            unique_together={('description', 'action_date', 'user')},
        ),
    ]
