# Generated by Django 2.2.10 on 2020-02-26 10:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stores', '0005_auto_20200226_1029'),
    ]

    operations = [
        migrations.AlterField(
            model_name='store',
            name='record_type',
            field=models.CharField(choices=[('use', 'Store'), ('debt', 'Debt'), ('online', 'Online')], default='use', max_length=20),
        ),
    ]
