# Generated by Django 2.2.24 on 2023-03-16 14:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stores', '0007_auto_20221222_1705'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='recurringstore',
            options={'ordering': ['name']},
        ),
    ]
