# Generated by Django 2.2.10 on 2020-03-06 08:55

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('stores', '0007_auto_20200305_0945'),
    ]

    operations = [
        migrations.AddField(
            model_name='store',
            name='action_date',
            field=models.DateField(default=datetime.datetime(2020, 3, 6, 8, 55, 30, 992045, tzinfo=utc)),
        ),
    ]
