# Generated by Django 2.2.24 on 2023-03-23 05:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('households', '0009_household_members'),
        ('stores', '0008_auto_20230316_1650'),
    ]

    operations = [
        migrations.AddField(
            model_name='store',
            name='household',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='stores', to='households.Household'),
        ),
    ]
