# Generated by Django 2.2.10 on 2020-03-06 08:56

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('stores', '0008_store_action_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='store',
            name='action_date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
