# Generated by Django 2.2.28 on 2023-04-08 19:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stores', '0009_store_household'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recurringstore',
            name='deleted_by',
        ),
        migrations.RemoveField(
            model_name='store',
            name='deleted_by',
        ),
    ]
