# Generated by Django 2.2.28 on 2023-06-29 06:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('households', '0001_initial'),
        ('household_members', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='householdmember',
            name='household',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='family', to='households.Household'),
        ),
    ]
