# Generated by Django 2.2.24 on 2023-03-22 17:02

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('household_members', '0004_auto_20230322_1849'),
    ]

    operations = [
        migrations.AlterField(
            model_name='householdmember',
            name='household',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='family', to='households.Household'),
        ),
        migrations.AlterField(
            model_name='householdmember',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='member', to=settings.AUTH_USER_MODEL),
        ),
    ]
