# Generated by Django 2.2.24 on 2023-03-22 17:06

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('households', '0005_remove_household_members'),
        ('household_members', '0005_auto_20230322_1902'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='HouseholdMember',
            new_name='Householder',
        ),
    ]
