# Generated by Django 2.2.24 on 2023-03-22 18:15

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('households', '0008_remove_household_members'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('household_members', '0006_auto_20230322_1906'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Householder',
            new_name='HouseholdMember',
        ),
    ]
