# Generated by Django 2.2.28 on 2023-04-08 19:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('household_members', '0007_auto_20230322_2015'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='householdmember',
            name='deleted_by',
        ),
    ]
