# Generated by Django 3.2.20 on 2024-03-17 12:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('budgeting', '0002_alter_budgetitem_unique_together'),
    ]

    operations = [
        migrations.AddField(
            model_name='budget',
            name='description',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
