# Generated by Django 3.2.20 on 2024-03-17 13:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('budgeting', '0003_budget_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='budgetitem',
            name='budget',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='budget_items', to='budgeting.budget'),
        ),
    ]
