# Generated by Django 4.2.17 on 2025-06-04 08:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('budgeting', '0004_alter_budgetitem_budget'),
    ]

    operations = [
        migrations.AddField(
            model_name='budgetitem',
            name='is_recurring',
            field=models.BooleanField(default=False),
        ),
    ]
