# Generated by Django 4.2.17 on 2025-06-04 15:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('budgeting', '0005_budgetitem_is_recurring'),
    ]

    operations = [
        migrations.AlterField(
            model_name='budgetitem',
            name='budget',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='budget_items', to='budgeting.budget'),
        ),
    ]
