# Generated by Django 4.2.17 on 2025-07-07 17:06

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('budgeting', '0006_alter_budgetitem_budget'),
    ]

    operations = [
        migrations.AddField(
            model_name='budgetitem',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='user_budget_items', to=settings.AUTH_USER_MODEL),
        ),
    ]
