# Generated by Django 4.2.17 on 2026-01-11 05:03

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('budgeting', '0008_userbudgetline_defaultbudgetline_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserDefaultBudgetLine',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, null=True)),
                ('updated_at', models.DateTimeField(default=django.utils.timezone.now, null=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('enabled', models.BooleanField(default=True)),
                ('line', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='user_default_budget_lines', to='budgeting.defaultbudgetline')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='user_default_budget_lines', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'user_default_budget_lines',
                'unique_together': {('line', 'user')},
            },
        ),
    ]
