name: D2D Store API CI/CD

# Controls when the workflow will run
on:
  # Triggers the workflow on push events but only for the develop branch
  push:
    branches: [develop]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Prepare SSH and deploy the app
        uses: appleboy/ssh-action@v0.1.10
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USERNAME }}
          password: ${{ secrets.SSH_PASSWORD }}
          port: ${{ secrets.SSH_PORT }}
          script: |
            cd ~/storePy
            git pull origin develop
            pipenv install
            pipenv run python manage.py migrate
            rm -rf django_static
            pipenv run python manage.py collectstatic
            pipenv run python manage.py crontab add
            echo "${{ secrets.SSH_PASSWORD }}" | sudo -S systemctl daemon-reload
            echo "${{ secrets.SSH_PASSWORD }}" | sudo -S systemctl restart gunicorn
            exit
            echo "Deployment is done!"
