name: D2D Store API CI/CD

# Controls when the workflow will run
on:
  # Triggers the workflow on push events but only for the develop branch
  push:
    branches: [develop]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Prepare SSH and deploy the app
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USERNAME }}
          key: ${{ secrets.SSH_KEY }}
          port: ${{ secrets.SSH_PORT }}
          script: |
            cd ~/storePy
            git pull origin develop
            pipenv shell
            pipenv install
            python manage.py migrate
            exit
            sudo systemctl daemon-reload
            sudo systemctl restart gunicorn
            exit
            echo "Deployment is done!"
